#!/bin/bash 

echo Pulling repository...
git pull
echo Copying config.json to project folder...
cp config.json Jigglypuff.Core/config.json
echo Changing Directory...
cd Jigglypuff.Core/
echo Restoring Nuget Packages...
dotnet restore
echo Running Jigglypuff...
dotnet run